### ISSUE TITLE
bower support

### ISSUE THREAD

**Issue by F4b1n0u** [allouis/minivents#19]
could you add a bowed support ?
I tried to add by myself the bower.json, but i can't contribute :s
`{
  "name": "minivents",
  "version": "1.1.6",
  "description": "Tiny eventing for javascript",

  "main": "minivents.js",
  
  "ignore": [
    "**/.*",
    "node_modules",
    "bower_components",
    "test"
  ],
  "dependencies": {},
  "devDependencies": {}
}`

**Comment by allouis** [comment]
Done, after merging #22
