### ISSUE TITLE
v1.2.0 release is old and busted but installs over latest (v.1.1.7) -- jspm

### ISSUE THREAD

**Issue by rudylattae** [allouis/minivents#25]
In a current project, I am using [jspm](http://jspm.io) as my package manager. It allows me to install  `minivents` as a dependency by doing:

> jspm install minivents=github:allouis/minivents

### Sweet! Except...

jspm expects that the libs it installs track releases using [Semantic Versioning](http://semver.org). This means that `v1.1.2` < `v1.1.7` < `v1.2.0`

The latest release for this lovely project is `v1.1.7`, which is stable. However, there also exists a release `v1.2.0` from Feb 26 2014 -- which is broken. So this means that when I install this project as a dependency, I get the old and busted version :(

Could you kindly delete that version?

### Workaround

Just in case someone else has this same issue, here's the workaround until its fixed:

> jspm install minivents=github:allouis/minivents@1.1.7

**Comment by allouis** [comment]
Nice catch! That version must've been a mistake from ages ago!I've removed it now, please let me know if this works :+1: Thanks for raising!

**Comment by allouis** [comment]
@rudylattae Let me know if this hasn't fixed it, if it has, please close :relaxed:

**Comment by rudylattae** [comment]
Thanks that fixed it!
