### ISSUE TITLE
Cascading Events.emit bug

### ISSUE THREAD

**Issue by ebhoren** [allouis/minivents#27]
I've found that an Events instance could not trigger an event, that will trigger another event on the same Events instance.

The solution can be fixed by declaring variables list, j, i locally in .off and .emit
I've forked your repo and fixed the bug.

Do you want a merge request?

**Comment by allouis** [comment]
> I've found that an Events instance could not trigger an event, that will trigger another event on the same Events instance.

I don't quite understand, could you give me some steps to replicate? 

If it's a bug i'd love a PR, would you also be able to include a failing test with it to protect against regression?

**Comment by ebhoren** [comment]
Add this to your tests suite and check the result of the last test

it('should result in registered callbacks being invoked', function () {
        var bus = new Events(),
            called = 0,
            f1 = function () { called++ },
            f2 = function () { called++ },
            f3 = function () { called++ },
            f4 = function () { bus.emit('cascade'); },
            f5 = function () { called++ };

        bus.on('ping', f1);
        bus.on('ping', f2);
        bus.on('ping', f3);
        bus.on('ping', f4);
        bus.on('ping', f5);
        bus.emit('ping');
        assert.equal(called, 4);
    });


You will see that the event.emit on f4 will prevent f5 from being executed by the "ping" event.

**Comment by allouis** [comment]
@ebhoren Great catch, happy to accept a PR, can you include the test? :relaxed:

**Comment by ebhoren** [comment]
I've sent the pull request. The test is included in my pull.
Thanks

**Comment by ebhoren** [comment]
Could you create a new release tag with this bug fix? Thanks

**Comment by allouis** [comment]
@ebhoren that's up and published to npm

**Comment by ebhoren** [comment]
Thanks. It was nice to contribute to your library.  :)

**Comment by allouis** [comment]
Thank you, it was great to have your contribution!
