### ISSUE TITLE
Issue when emitting and removing

### ISSUE THREAD

**Issue by ebhoren** [allouis/minivents#29]
Hi,
I've found a bug when you register multiple callbacks to an event, then emit the event, and one of the callback unregister himself for this event, resulting in skipping the next callback.

I've forked your repo and fixed it.
Thanks

**Comment by Amareis** [comment]
@allouis Can you merge that?

**Comment by allouis** [comment]
@ebhoren @Amareis really sorry about this 😞

**Comment by allouis** [comment]
Merged
