### ISSUE TITLE
Request to add .once() method

### ISSUE THREAD

**Issue by uglymunky** [allouis/minivents#31]
I have some events I'd like to only have bound one time.

I'm imagining you're intending for this to be small library, so not sure where this fits into your design goals.

I wouldn't mind extending it myself, only that's not an option because the `events` object is hidden inside the `Events` constructor.

If I were to use .off() before calling .on() so as to prevent adding the event handler multiple times I could accidentally remove events I needed to hold onto.

**Comment by uglymunky** [comment]
nm, it actually makes more sense to just call .off() each time since there really shouldn't be any other event handlers anyway.

**Comment by mikegleasonjr** [comment]
I also think in userland that is something pretty easy to do.

```
function once(event, callback) {
   ...
}
```

The function body is left as an exercise to the reader ;)
