### ISSUE TITLE
Wrong meta

### ISSUE THREAD

**Issue by Amareis** [allouis/minivents#32]
```
bower minivents#*   invalid-meta The "main" field cannot contain minified files
bower minivents#*   mismatch Version declared in the json (2.0.1) is different than the resolved one (2.0.2)
```

`version` field now deprecated in bower, you can remove it. Also, you have `bower.json` and `.bower.json` files, is it really matters?

**Comment by allouis** [comment]
Cool, I'll remove that. I can't see a `.bower.json` file though..?

**Comment by Amareis** [comment]
Oh, sorry :)
Bower generates `.bower.json` for dependencies, so i see it in my `bower_components` and don't check it in repo.
https://github.com/bower/bower/issues/1174

**Comment by allouis** [comment]
@Amareis Sorry it took so long to get round to this, I've cleaned up the bower.json in v2.0.3
