### ISSUE TITLE
How to use context

### ISSUE THREAD

**Issue by eko24** [allouis/minivents#33]
Hello,

I thought this code will launch two alert windows with values 1 and 2 respectively:
```javascript
var sandbox = new Events();
sandbox.on("event", function(){
    alert(1)
});

var another= new Events();
another.on("event", function(){
    alert(2)
}, sandbox);

sandbox.emit("event");
```

I thought it'll be similar to Backbone [`listenTo`](http://backbonejs.org/#Events-listenTo)

Here is my [plunkr](https://plnkr.co/edit/UhdyWx54WQsJj4iTD03o?p=preview) demo.
Could you please provide more details for what `context` could be used ?

**Comment by allouis** [comment]
Hi @eko24 thanks for raising this question.

`context` is the object that will be `this` when the function is called.

For example:

```javascript
var person = {
  name: 'eko24'
}
var sandbox = new Events()

sandbox.on('thing', function () {
  alert(this.name)
}, person)

sandbox.emit('thing') // alerts 'eko24'
```

If you wanted something like listenTo you could do something like this:

```javascript
var myObject = {
  listenTo: function (emitter, event, fn) {
    return emitter.on('event', fn, this)
  },
  name: 'eko24'
}

var sandbox = new Events()

myObject.listenTo(sandbox, 'thing', function () {
  alert(this.name)
})

sandbox.emit('thing') // alerts 'eko24'
```

I hope this clears things up ☺️

**Comment by eko24** [comment]
Thank you @allouis for your reply.
I'll try your solution soon, I'll be away from my PC for a few weeks.
It looks like just what I need, so I close this issue and reopen it in case I'll run into any minivents-related bug.
Best wishes 😉

**Comment by eko24** [comment]
One more update from me - this works like a charm !
I've added your `listenTo` method into lib and this is just amazing !
Thank you so much !

**Comment by allouis** [comment]
Awesome! Glad to hear ☺️
